#!/bin/bash

DIR="env/bin/activate"

if [ -f "$DIR" ] 
then
	echo "Activate" $DIR
	source $DIR
else
	echo "Make venv"
	python3 -m venv env
	echo "Activate" $DIR
	source $DIR
	echo "Install requirements"
	pip install -r requirements.txt
fi

python3 python/random_sampler.py